spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: "finance"
    password: "Password12345"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/finance"
